// <auto-generated />
using ApiGestionDashboard.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGestionDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106064141_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiGestionDashboard.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("clave");

                    b.Property<int>("Dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("usuario_email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("rol_empleado");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "588acee9920f023bfe4b60ff2def822ee7612d12f620db6677d637e799315884",
                            Dni = 12345678,
                            Email = "matias@hotmail.com.ar",
                            Nombre = "Matias",
                            Rol = 0
                        },
                        new
                        {
                            Id = 2,
                            Clave = "5798325bcbffca1fcd3fa2f03e1c0aeb0fce43443425a2696fd637c7135b10f4",
                            Dni = 21456789,
                            Email = "jose@gmail.com.ar",
                            Nombre = "Jose",
                            Rol = 0
                        },
                        new
                        {
                            Id = 3,
                            Clave = "e5dfcfbaaa1b861a1b813d4921a5417f5af017bec697ddf14d13a698b8f04cde",
                            Dni = 30145741,
                            Email = "martin@gmail.com.ar",
                            Nombre = "Martin",
                            Rol = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
